# Generated by Django 5.2.4 on 2025-07-20 18:47

import app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Profile Name')),
                ('surname', models.CharField(blank=True, max_length=200, null=True, verbose_name='Profile Surname')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Profile Description')),
                ('email', models.EmailField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=app.models.return_date_time, null=True, verbose_name='Profile Creation Date')),
                ('notified', models.BooleanField(blank=True, default=False, null=True, verbose_name='Subscribed?')),
                ('active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Active?')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Model')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Tweet')),
                ('url_name', models.SlugField(blank=True, help_text='This will be filled automatically', max_length=500, verbose_name='Sayfa Uzantısı')),
                ('active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Kullan')),
                ('create_date', models.DateField(default=app.models.return_date_time, verbose_name='Tarih')),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Sıralama')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.profile')),
            ],
            options={
                'verbose_name': 'Tweet',
                'verbose_name_plural': 'Tweets',
                'ordering': ['-order'],
            },
        ),
    ]
